### PR TITLE
Kolinbranch

### PR DESCRIPTION
**Pull request by kschafrick**
I added in rough vehicle icons, back buttons, and general layouts for the pages

### CODE REVIEW

**Comment by thefridge111** [comment]
Everything looks good but I have a few concerns with why you changed the jvm version number from 1.8->1.7 in the gradle file and why you changed the vcs tags?

**Comment by kschafrick** [comment]
I didn't change anything like that.. So I have no clue what you're talking about

**Comment by thefridge111** [comment]
If you look in the files changed theres a bunch of things that changed. My guess is that you dont have java 1.8 installed so those are just local config files. Try checking your java version and if its still at 1.7 try to install 1.8.

**Comment by kschafrick** [comment]
Java has been updated, now how do I update the unknown files?

**Comment by thefridge111** [comment]
There'll be something in the IDE settings that you can specify what version of java you're using.

**Comment by kschafrick** [comment]
Git shell says I'm using 1.8 now, so i added/committed/pushed again

**Pull request merged**
